services:
  react-app:
    build:
      context: ./nest-app
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: nest-app/src
          target: /app/src
        - action: sync+restart
          path: nest-app
          target: /app
        - action: rebuild
          path: nest-app/package.json